stages:
  - build
  - deploy

build:
  stage: build
  image: node:19
  script:
    - echo "Building the project"
    - npm ci
    - npm run build
  only:
    - merge_requests

deploy:
  stage: deploy
  image: node:19
  script:
    - echo "Deploying to Vercel"
    - npx vercel --token $VERCEL_TOKEN --yes=n --prod
  environment:
    name: prod
  only:
    - master
  variables:
    VERCEL_TOKEN: $VERCEL_TOKEN
